# toolchain.cmake

# Set LEVELDB_BUILD_TESTS to OFF
set(LEVELDB_BUILD_TESTS OFF)

# Set LEVELDB_BUILD_BENCHMARKS to OFF
set(LEVELDB_BUILD_BENCHMARKS OFF)

# Set CPR_BUILD_TESTS to OFF
set(CPR_BUILD_TESTS OFF)

# Set BUILD_SHARED_LIBS to OFF
#set(BUILD_SHARED_LIBS OFF)

# Set CMAKE_BUILD_TYPE
set(CMAKE_BUILD_TYPE Release)

